/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.nekoiceteam.nekoicebot

import kotlin.time.*
import kotlin.system.*
import dev.minn.jda.ktx.interactions.*
import dev.minn.jda.ktx.*
import kotlinx.coroutines.*
import net.dv8tion.jda.api.*
import net.dv8tion.jda.api.entities.*
import net.dv8tion.jda.api.events.*
import net.dv8tion.jda.api.events.guild.*
import net.dv8tion.jda.api.exceptions.*
import net.dv8tion.jda.api.requests.*
import net.dv8tion.jda.api.utils.*
import java.lang.Integer.max
import java.util.*
import java.util.concurrent.*
import kotlin.concurrent.thread
import kotlin.time.Duration.Companion.minutes

@ExperimentalTime
fun main() {
    val jda = light("TOKEN", enableCoroutines=true) {
        intents += listOf(GatewayIntent.GUILD_MEMBERS)
}
    
    jda.onCommand("ping") { event->
        val time = measureTime {
            event.reply("Pong!").await()
        }.inWholeMilliseconds

        event.hook.editOriginal(":ping_pong: Pong: $time ms").queue()
    }
}

