/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nekoiceteam.nekoicebot;


import net.dv8tion.jda.annotations.*;
import net.dv8tion.jda.api.*;
import net.dv8tion.jda.api.audio.*;
import net.dv8tion.jda.api.audio.factory.*;
import net.dv8tion.jda.api.audio.hooks.*;
import net.dv8tion.jda.api.audit.*;
import net.dv8tion.jda.api.entities.*;
//import net.dv8tion.jda.api.entities.channel.*;
import net.dv8tion.jda.api.entities.templates.*;
import net.dv8tion.jda.api.events.*;
import net.dv8tion.jda.api.events.channel.*;
import net.dv8tion.jda.api.events.emote.*;
import net.dv8tion.jda.api.events.guild.*;
import net.dv8tion.jda.api.events.http.*;
import net.dv8tion.jda.api.events.interaction.*;
import net.dv8tion.jda.api.events.message.*;
import net.dv8tion.jda.api.events.role.*;
import net.dv8tion.jda.api.events.self.*;
import net.dv8tion.jda.api.events.stage.*;
import net.dv8tion.jda.api.events.thread.*;
import net.dv8tion.jda.api.events.user.*;
import net.dv8tion.jda.api.exceptions.*;
import net.dv8tion.jda.api.interactions.*;
import net.dv8tion.jda.api.interactions.callbacks.*;
import net.dv8tion.jda.api.interactions.commands.*;
import net.dv8tion.jda.api.interactions.components.*;
import net.dv8tion.jda.api.managers.*;
import net.dv8tion.jda.api.managers.channel.*;
import net.dv8tion.jda.api.requests.*;
import net.dv8tion.jda.api.requests.restaction.*;
import net.dv8tion.jda.api.sharding.*;
import net.dv8tion.jda.api.utils.*;
import net.dv8tion.jda.api.utils.cache.*;
import net.dv8tion.jda.api.utils.concurrent.*;
import net.dv8tion.jda.api.utils.data.*;
import net.dv8tion.jda.internal.audio.*;
import net.dv8tion.jda.internal.entities.*;
//import net.dv8tion.jda.internal.entities.mixin.*;
import net.dv8tion.jda.internal.handle.*;
import net.dv8tion.jda.internal.hooks.*;
import net.dv8tion.jda.internal.interactions.*;
import net.dv8tion.jda.internal.interactions.command.*;
import net.dv8tion.jda.internal.interactions.component.*;
import net.dv8tion.jda.internal.managers.*;
import net.dv8tion.jda.internal.managers.channel.*;
import net.dv8tion.jda.internal.requests.*;
import net.dv8tion.jda.internal.requests.ratelimit.*;
import net.dv8tion.jda.internal.requests.restaction.*;
import net.dv8tion.jda.internal.utils.*;
import net.dv8tion.jda.internal.utils.cache.*;
import net.dv8tion.jda.internal.utils.compress.*;
import net.dv8tion.jda.internal.utils.concurrent.*;
import net.dv8tion.jda.internal.utils.config.*;
import net.dv8tion.jda.internal.utils.tuple.*;
import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import javax.security.auth.login.LoginException;

public class App {
	public static void main(String[] args) {
		JDABuilder builder = JDABuilder.createDefault(args[0]);
		
		builder.disableCache(CacheFlag.MEMBER_OVERRIDES, CacheFlag.VOICE_STATE);
		builder.setBulkDeleteSplittingEnabled(false);
		builder.setCompression(Compression.ZLIB);
		builder.setActivity(Activity.playing("With Your Mom"));    
		try {
			builder.build();
		} catch (LoginException e) {
	    e.printStackTrace();
		}
	}
}
