/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    jcenter()
    google()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("net.dv8tion:JDA:5.0.0-alpha.12")
    implementation("org.slf4j:slf4j-simple:1.7.9")
    implementation(group = "org.jetbrains.intellij.deps", name = "trove4j", version = "1.0.20200330")
    //implementation("com.jagrosh:jda-utilities:")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.8.1")
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("org.nekoiceteam.nekoicebot.App")
}

tasks {
    named<ShadowJar>("shadowJar") {
        archiveBaseName.set("shadow")
        mergeServiceFiles()
        manifest {
            attributes(mapOf("Main-Class" to "org.nekoiceteam.nekoicebot.App"))
        }
    }
}

tasks {
    build {
        dependsOn(shadowJar)
    }
}

