name: CHECKER CODE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  import-gpg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Decrypy SC
        run : gpg --multifile --decrypt NekoIceBot-SourceCode.zip.gpg && unzip NekoIceBot-SourceCode.zip -y

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm i
      - run: npm run build --if-present
      - run: npm run github
